@@include('./swiper_main/swiper.settings.js')
@@include('./swiper_main/swiper_content.js')
@@include('./swiper_main/pagination.js')
@@include('burger.js')
@@include('./animation.js')
@@include('image.adaptive.js')
@@include('smart.js')
@@include('scrollIntoView.js')
@@include('listeners.js')

